### PR TITLE
Preselect current day

### PR DESCRIPTION
**Pull request by kamdaou-amalitech**
Preselected current day

### CODE REVIEW

**Comment by Evansmbongo** [comment]
When the current month is changed to a different month and changed back to the current month, the current day does not highlight anymore

https://github.com/AmaliTech-Training-Rw/Meeting-Room-booking-App/assets/120010640/3e5f4b3f-f00b-44a3-813a-2916a2e08dcc

**Review by esthcarelle — APPROVED** [review]

**Review by bensek — APPROVED** [review]

**Comment by kamdaou-amalitech** [comment]
@Evansmbongo This is happening because every time the user scrolls to a new month, we unselect what he's picked, as we don't want to select what is not seen by the user. Is it better to keep it selected even though the user has scrolled to another month?

**Comment by kamdaou-amalitech** [comment]
Okay. If they confirm this is the way it should be, I will implement it this way.

**Comment by Evansmbongo** [comment]
Alright

**Pull request merged**
